steps:
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/latihan-chandra/api-temantb/PROJECT_ID:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/latihan-chandra/api-temantb/PROJECT_ID:$SHORT_SHA"]
